# Generated by Django 2.2 on 2019-04-14 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='login_time',
        ),
    ]
