# Generated by Django 2.1.7 on 2019-03-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pycode',
            name='result_error',
            field=models.TextField(default='No Error'),
        ),
        migrations.AddField(
            model_name='pycode',
            name='result_output',
            field=models.TextField(default='No Output'),
        ),
    ]
