# Generated by Django 2.1.7 on 2019-03-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0002_uservids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uservids',
            name='uservid',
            field=models.FileField(upload_to=''),
        ),
    ]
