# Generated by Django 2.1.7 on 2019-03-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0003_userlogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='id',
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userlogin',
            name='uname',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
