# Generated by Django 2.1.7 on 2019-03-25 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runcode', '0004_auto_20190325_0131'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogin',
        ),
    ]
